# $Id: Makefile,v 1.4 2002/03/29 16:32:02 cmatsuoka Exp $

XCFLAGS = -I../include
OBJS	=
DFILES	= Makefile
CFILES	=
DDIRS	= msdos win32 unix macos amiga dc
XDFILES =
LIB	=

all:
	(cd $(FILEIO_DRIVER); $(MAKE) all)

include ../../Rules

