# $Id: Makefile,v 1.1 2003/09/02 01:10:55 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= allegro.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules
