#
# Makefile for DJGPP v2
#
# $Id: Makefile.dj,v 1.5 2001/07/22 15:46:22 darkfiber Exp $
#

include $(TOPDIR)/Rules.dj

OBJS = dummy.o

all: sound.a

sound.a: $(OBJS)
	ar rsv sound.a $(OBJS)

clean:
	@if exist *.a del *.a
	@if exist *.o del *.o
	@if exist *.bak del *.bak

