# $Id: Makefile,v 1.3 2001/09/13 17:24:03 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= dummy.o
DFILES	= Makefile $(OBJS:.o=.c) Makefile.wat Makefile.dj
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

