# $Id: Makefile,v 1.4 2002/04/10 01:51:01 cmatsuoka Exp $

XCFLAGS	= -I ../../include
OBJS	=
DFILES	= Makefile main.c portdefs.h resource.h library.c sarien.r
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

