# $Id: Makefile,v 1.4 2003/07/13 19:53:03 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= sdl.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules
