# $Id: Makefile,v 1.3 2001/09/13 17:24:01 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= dive.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

