# $Id: Makefile,v 1.5 2002/11/06 07:57:31 cmatsuoka Exp $

XCFLAGS	= -I../../include -Wno-implicit-int
OBJS	= win32.o
DFILES	= Makefile $(OBJS:.o=.c)
CFILES	=
DDIRS	=
XDFILES	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules

