# $Id: Makefile,v 1.3 2002/11/06 07:41:23 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= sound_macos.o
DFILES	= Makefile sound_macos.c
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

