# $Id: Makefile,v 1.4 2001/11/30 14:59:24 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= amiga.o timer.o
DFILES	= Makefile $(OBJS:.o=.c) amiga_keys.h
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

