# $Id: Makefile,v 1.3 2003/07/06 13:11:48 cmatsuoka Exp $

XCFLAGS	= -I ../../include
OBJS	= SDLMain.o MyWindowController.o
DFILES	= Makefile $(OBJS:.o=.m) $(OBJS:.o=.h)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../../Version
include ../../../../Rules

