# $Id: Makefile,v 1.2 2002/04/04 15:42:03 cmatsuoka Exp $

XCFLAGS	= -I ../../include
OBJS	=
DFILES	= Makefile sarien.c callback.h sarienRsc.h
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

