# $Id: Makefile,v 1.3 2001/12/08 14:14:32 cmatsuoka Exp $

XCFLAGS =
OBJS	=
DFILES	= Makefile config.guess config.sub install-sh cflow2dot.pl plotmem.pl
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../Rules

