# $Id: Makefile,v 1.2 2002/11/06 23:12:35 cmatsuoka Exp $

XCFLAGS	= -I../../include
OBJS	= SarienWindow.o SarienApplication.o SarienView.o cocoa.o
DFILES	= Makefile $(OBJS:.o=.m) $(OBJS:.o=.h)
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Version
include ../../../Rules

