# $Id: Makefile,v 1.2 2001/12/06 14:00:17 cmatsuoka Exp $

XCFLAGS	= -I../../include -I/home/claudio/emu/microwin/src/include/
OBJS	= script.o
DFILES	= Makefile $(OBJS:.o=.c) README demo2.script
CFILES	=
DDIRS	=
LIB	= ../../../lib/libsarien.a

all: $(LIB)

include ../../../Rules

