# $Id: Makefile,v 1.8 2003/07/16 13:04:18 cmatsuoka Exp $

XCFLAGS =
OBJS	=
DFILES	= Makefile agi.h getopt.h keyboard.h logic.h lzw.h menu.h \
	  opcodes.h picture.h rand.h savegame.h sound.h sarien.h portdefs.h \
	  view.h win32.h console.h text.h graphics.h sprite.h list.h scale2x.h
CFILES	=
DDIRS	=
XDFILES =
LIB	=

all:

include ../../Rules

