# $Id: Makefile,v 1.1 2002/04/26 20:27:43 cmatsuoka Exp $

XCFLAGS =
OBJS	=
DFILES	= Makefile PocketSarien.rc PocketSarien.vco PocketSarien.vcp \
	  SarienImages.bmp browse.cpp browse.h newres.h portdefs.h \
	  resource.h wince.cpp winmain.cpp
CFILES	=
DDIRS	= gapi missing
XDFILES =
LIB	=

all:

include ../Rules

